### ISSUE TITLE
Release on PyPI?

### ISSUE THREAD

**Issue by madig** [trufont/tfont#4]
What's needed to release an initial version on PyPI?

**Comment by anthrotype** [comment]
I just pushed a minimal `.travis.yml` file (with auto-upload to pypi on tags), however I don't seem to have enough permissions to activate Travis CI on the tfont repo.

![pmroywog](https://user-images.githubusercontent.com/6939968/46919585-40fd6000-cfd9-11e8-8c2d-db0562416466.png)

maybe @adrientetar can help

**Comment by adrientetar** [comment]
It should be enabled now.

**Comment by anthrotype** [comment]
the auto-upload to PyPI on tagged commits is now working.
I pushed v0.1.0
https://pypi.org/project/tfont/

**Comment by adrientetar** [comment]
thanks!
