### ISSUE TITLE
Kerning is unstructured as Dict[rapidjson.RawJSON, int], making JSON dumping fail

### ISSUE THREAD

**Issue by madig** [trufont/tfont#5]
Try e.g. with the Ubuntu font
```Python
tf = tfont.converters.UFOConverter().open("Ubuntu-B.ufo")
tfont.converters.TFontConverter().save(tf, "/tmp/test.tfont")
```
```
In [7]: TFontConverter().save(t, "/tmp/test.tfont")                             
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-c90fe6857802> in <module>
----> 1 TFontConverter().save(t, "/tmp/test.tfont")

~/Entwicklung/tfont/src/tfont/converters/tfontConverter.py in save(self, font, path)
    141         d = self.unstructure(font)
    142         with open(path, 'w') as file:
--> 143             json.dump(d, file, indent=self._indent)
    144 
    145     def structure_attrs_fromdict(self, obj, cl):

TypeError: keys must be strings
```
Kerning in `d["masters"]["Bold"]["hKerning"]` looks like this:
```
[...,
<rapidjson.RawJSON object at 0x7f238b90a540>: 29
...]
```
Deleting kerning makes dumping work.

**Comment by madig** [comment]
Loading the file still fails though:
```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/windows/fontWindow.py", line 584, in OnOpen
    trufont.TruFont.openFont()
  File "/home/nikolaus/Entwicklung/trufont/src/trufont/objects/application.py", line 127, in openFont
    font = TFontConverter().open(path)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/converters/tfontConverter.py", line 138, in open
    return self.structure(d, Font)
  File "/home/nikolaus/.virtualenvs/trufont/lib64/python3.7/site-packages/cattr/converters.py", line 178, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/converters/tfontConverter.py", line 161, in structure_attrs_fromdict
    conv_obj[name] = dispatch(type_)(val, type_)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/converters/tfontConverter.py", line 22, in _structure_seq_dict
    return dict((e[attr], self.structure(e, cls)) for e in data)
  File "/home/nikolaus/Entwicklung/tfont/src/tfont/converters/tfontConverter.py", line 22, in <genexpr>
    return dict((e[attr], self.structure(e, cls)) for e in data)
TypeError: string indices must be integers
```
data is:
```Python
{'Bold': {'alignmentZones': [[-14, 14], [526, 14], [693, 16], [-188, 3]],
          'ascender': 776,
          'capHeight': 693,
          'descender': -185,
          'guidelines': [{'angle': 0, 'x': 0, 'y': 346},
                         {'angle': 0, 'x': 0, 'y': 736},
                         {'angle': 0, 'x': 0, 'y': 962}],
          'name': 'Bold',
          'xHeight': 526}}
```
In this case, `attr` is `"name"`, so I suppose `data` should have been the dict of 'Bold'.

Here's the test tfont file (no kerning): [test.zip](https://github.com/trufont/tfont/files/2475742/test.zip)

**Comment by adrientetar** [comment]
This is what broke it: https://github.com/fonttools/ufoLib2/commit/50dec8c9e2390cf41e2b29d1dd64dbe89120ad16 (kerning changed format)

Should use my original ufoLib2 w/o the breaking changes to make it behave like previous ufo libraries. e.g. the font I showed you before was made with the original and has kerning that works (which is why I found this report surprising).

**Comment by madig** [comment]
Oh boy. So, which ufoLib2 should be the canonical one?

@anthrotype

**Comment by anthrotype** [comment]
I changed ufoLib2 readKerning in that commit so that it matched the behaviour of ufoLib, which returns a single dictionary keyed by (left, right) tuples, instead of nested dictionaries.
If tfont needs it the other way, it should be trivial to recreate that nested dict structure upon doing the conversion from UFO.
Note that once we move ufoLib to fontTools, and add the objects API similar to defcon, then ufoLib2 has no more reason to exist as standalone module and we shall move tfont to use fontTools.ufoLib instead.

**Comment by madig** [comment]
I'd like to keep strong ties to the UFO world as that's what we store our
fonts in, so I'd prefer to change tfont. Adrien? Are there reasons to keep
it as it currently is?

**Comment by anthrotype** [comment]
this should work. Shall I send a PR?

```diff
diff --git a/src/tfont/converters/ufoConverter.py b/src/tfont/converters/ufoConverter.py
index da18127..53a7b71 100644
--- a/src/tfont/converters/ufoConverter.py
+++ b/src/tfont/converters/ufoConverter.py
@@ -74,7 +74,12 @@ class UFOConverter(cattr.Converter):
         # note: unlike ufo, we store kerning in visual order. hard to convert
         # between the two (given that ltr and rtl pairs can be mixed)
         if ufo.kerning:
-            master.hKerning = ufo.kerning
+            hKerning = {}
+            for (first, second), value in ufo.kerning.items():
+                if first not in hKerning:
+                    hKerning[first] = {}
+                hKerning[first][second] = value
+            master.hKerning = hKerning
         if info.ascender:
             master.ascender = info.ascender
         if info.capHeight:
```

**Comment by anthrotype** [comment]
I just noticed `ufoLib2` is imported at the module-level scope inside `tfont.converters.ufoConverter` but it is not specified in the setup.py `install_requires`:
https://github.com/trufont/tfont/blob/0f645842010f25f986658403f2a46a3e6492013e/src/tfont/converters/ufoConverter.py#L12

**Comment by anthrotype** [comment]
apart from the hKerning issue, the other one that @madig pointed out is unrelated to ufoLib2 and I can repro with this simple code:

```python
from tfont.converters import TFontConverter
from tfont.objects import Font

converter = TFontConverter()
font = Font()
converter.save(font, "test.tfont")
font2 = converter.open("test.tfont")
```

**Comment by anthrotype** [comment]
> I just noticed ufoLib2 ... is not specified in the setup.py install_requires:

I just added that to setup.py as part of #4 
https://github.com/trufont/tfont/commit/d206a6dda038ff3a502d03884b7db3bcaa653aeb

**Comment by anthrotype** [comment]
If you prefer to keep ufoLib2 optional instead of required we can add it to extras_require under a key named “ufo”. So pip install tfont[ufo] will also install ufoLib2 and its deps.

But then we need to avoid importing ufoConverter module until it’s needed, otherwise we get an ImportError

**Comment by adrientetar** [comment]
sgtm

> he other one that @madig pointed out

this is due to https://github.com/python/typing/issues/570 apparently (pep560/python 3.7 breaking change)

**Comment by adrientetar** [comment]
cebbd381aa2b4bb3d918a75cb4f7b504303fd576

**Comment by anthrotype** [comment]
> this is due to python/typing#570 apparently (pep560/python 3.7 breaking change)

@adrientetar ah! Now I remember.. Thanks for the quick fix.

> sgtm

Ok, I'll move ufoLib2 to extras_require. Shall I also apply the un-flattening of hKerning dict?

**Comment by adrientetar** [comment]
yeah
